[simulation]
fs_mic = 48000
up_fs = 1000000
sound_file = "examples/gunshot1.wav"

[source]
position = [6378137.0, 10.0, 10.0]

[[sensor]]
name = "SensorA"
position = [6378137.0, 0.0, 0.0]      # ECEF meters
quaternion = [0, 0, 0, 1]
mics = [
    [  0.05,  0.05, 0.0 ],
    [ -0.05,  0.05, 0.0 ],
    [ -0.05, -0.05, 0.0 ],
    [  0.05, -0.05, 0.0 ]
]

[[sensor]]
name = "SensorB"
position = [6378138.0, 0.0, 1.0]
quaternion = [0, 0, 0, 1]
mics = [
    [  0.05,  0.05, 0.0 ],
    [ -0.05,  0.05, 0.0 ],
    [ -0.05, -0.05, 0.0 ],
    [  0.05, -0.05, 0.0 ]
]

[[sensor]]
name = "SensorC"
position = [6378138.0, 1.0, 2.0]
quaternion = [0, 0, 0, 1]
mics = [
    [  0.05,  0.05, 0.0 ],
    [ -0.05,  0.05, 0.0 ],
    [ -0.05, -0.05, 0.0 ],
    [  0.05, -0.05, 0.0 ]
]

[[sensor]]
name = "SensorD"
position = [6378137.0, 1.0, 3.0]
quaternion = [0, 0, 0, 1]
mics = [
    [  0.05,  0.05, 0.0 ],
    [ -0.05,  0.05, 0.0 ],
    [ -0.05, -0.05, 0.0 ],
    [  0.05, -0.05, 0.0 ]
]
